# Generated by Django 5.0.6 on 2026-08-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('GENERAL', 'General'), ('SCIENCE', 'Science'), ('COMMERCIAL', 'Commercial'), ('ARTS', 'Arts')], default='GENERAL', help_text='General for JSS students; Science, Commercial or Arts for SSS students.', max_length=20),
        ),
    ]
