# Generated by Django 5.0.6 on 2026-08-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_target_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='department',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SCIENCE', 'Science'), ('COMMERCIAL', 'Commercial'), ('ARTS', 'Arts')], default='GENERAL', max_length=20),
        ),
    ]
